### PR TITLE
It's called vCPUs

### PR DESCRIPTION
**Pull request by melroy89**
It's not `VCPUS`, it should be: `vCPUs`

### CODE REVIEW

**Comment by dereknola** [comment]
Amazon directly refers in [their documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-optimize-cpu.html) to the cores as `vCPUs` 

> Each thread is represented as a virtual CPU (vCPU) on the instance

**Comment by brandond** [comment]
I think the nit was just the capitalization.

**Comment by melroy89** [comment]
> I think the nit was just the capitalization.

Correct. Please reopen and merge.

**Review by dereknola — APPROVED** [review]

**Comment by dereknola** [comment]
@melroy89 Apologies, I completely misread your PR and thought that you were replacing vCPUS with VCPUS . The exact reverse of what your PR is actually doing. Clearly I was having a bad Friday. Approved and Merged, thank you finding this.

**Pull request merged**
