### PR TITLE
Revise colors for dark mode svg

### PR DESCRIPTION
**Pull request by dereknola**
I still wasn't happy with the dark mode svgs I made for the new site. This is a slight revision to them.
See how it looks at https://dereknola.github.io/docs-k3s/architecture
Signed-off-by: Derek Nola <derek.nola@suse.com>

### CODE REVIEW

**Review by brandond — APPROVED** [review]

**Comment by VestigeJ** [comment]
Hey per my last email I wanted to comment on what we discussed prior regarding the preservation of the k3s gold-yellow for hyperlinks on the docs page in dark mode.

Additionally as we discussed regarding your extended warranty please test out that header gray to replace the "highlight gray" in the diagrams.

At your earliest convenience, as soon as possible,

Thank You

**Comment by brandond** [comment]
Can I get them in a cornflower blue?

**Comment by dereknola** [comment]
> Can I get this icon in cornflower blue?

ugh

**Comment by cwayne18** [comment]
I think it should be a pattern instead, like camo or plaid

**Comment by dereknola** [comment]
> I think it should be a pattern instead, like camo or plaid

NO MORE!
ugh2

**Comment by cwayne18** [comment]
> > I think it should be a pattern instead, like camo or plaid
> 
> NO MORE! ugh2

What do you mean I don't see anything

**Pull request merged**
