### PR TITLE
🔗 Update link to GitHub repository.

### PR DESCRIPTION
**Pull request by bdsoha**

### CODE REVIEW

**Review by brandond — APPROVED** [review]

**Comment by cwayne18** [comment]
Nice catch, thanks for the PR! Would you mind re-committing with -s to ensure the DCO check can pass? Soon as we get that we should be able to get this merged quickly.

Thanks again!

**Comment by bdsoha** [comment]
@cwayne18 Fixed, alongside changes to all pertinent links.

**Comment by brandond** [comment]
You need to squash/fixup your commits to ensure that all of them in the PR are signed. The second one is, but the first still is not.

Thanks!

**Comment by bdsoha** [comment]
> You need to squash/fixup your commits to ensure that all of them in the PR are signed. The second one is, but the first still is not.
> 
> Thanks!

Done!

**Review by briandowns — APPROVED** [review]

**Comment by brandond** [comment]
Merging despite the broken link; tigera has moved to versioned docs so we'll need another PR to fix that.

**Pull request merged**
